# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled ahmedabou706
 e.g., [user1, user2]
patreon: # Replace with a single Patreon ahmedabou706
open_collective: # Replace with a single Open Collective ahmedabou706
ko_fi: # Replace with a single Ko-fi ahmedabou706
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay ahmedabou706
issuehunt: # Replace with a single IssueHunt ahmedabou706
otechie: # Replace with a single Otechie ahmedabou706
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
